# Generated by Django 5.0.6 on 2024-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='user_not_subscribe_self'),
        ),
    ]
