# Generated by Django 5.0.6 on 2024-05-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recieps', '0003_rename_favrecipes_favoriterecipes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shoppinglist', 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списоки покупок'},
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
